### ISSUE TITLE
Trello app in Firebox failed to sign me back.

### ISSUE THREAD

**Issue by PeterMTaylor** [oskarjakiela/trello-web-clipper#5]
G'Day, 

I am addicted using this app within Firefox (updated to 45.0.1)  that creates cards I need when I find something interesting on the desktop internet.

At the moment, I am having trouble re-logging back in as it failed or no response. This started sometime last week. is there a reason for this?

Please assist to restore this good functionality thanks.

Peter.

![cropped trello app](https://cloud.githubusercontent.com/assets/2254567/13975300/d297b92e-f107-11e5-986e-9818f8ccf6ae.png)

**Comment by Miclaud** [comment]
Yeah please, I too am addicted too to this extension, it's VERY useful.

After last update (now I'm with Firefox 45.0.2) I cannot re-login anymore...

**Comment by oskarjakiela** [comment]
@PeterMTaylor, @Miclaud I'm going to fix the bug in coming weekend. Please, be patient :) and thank you for using my extension!

**Comment by Miclaud** [comment]
Thank you for creating it, I dismissed my Pocket account as I started to use it ;)

Good work.

**Comment by LadySaphira** [comment]
Hello,
I have the same problem as @PeterMTaylor and I'm waiting for the fix :-) I really love the WebClipper and his function....

Greez
LadySaphira

**Comment by jherrman** [comment]
Hi,
Me and several of my colleagues have this problem as well, but we can't seem to reproduce it properly, as it persists even if the web clipper is reinstalled. However, some people (using the same Firefox version on the same system and the same computer type) don't have the problem at all.

This add-on makes our task management workflow quite a bit more comfortable, so we would be very thankful if it got fixed.

Thank you

**Comment by oskarjakiela** [comment]
Hello everyone!

I'm so sorry for the delay. I hope you understand.

The issue should be fixed in version 0.3.1. New release is already available in [Chrome Web Store](https://chrome.google.com/webstore/detail/trello-web-clipper-for-ch/bgldhlkimfdidhgmndninednbehpcenk) and waiting for review in [Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/trello-web-clipper/versions/?page=1#version-0.3.1).

**Comment by jherrman** [comment]
Hi, sorry to be a bother, but the extension still does not seem to be working correctly (at least in some cases).

Instead of doing nothing at all, clicking the Log In button now makes the clipper pane blink once, and then reappear (with the "Keep me log in" value reset to 30 days).

I am using version 0.3.1 of the extension, and version 47.0 of Firefox. Can anyone verify this is the case for the as well? If not, what could be causing Clipper to behave in this way?

**Comment by rail** [comment]
The same here using 0.3.1... I haven't been able to use the extension for more than a month now. :(

**Comment by rail** [comment]
I tried to to debug the issue and found that it tries to connect to https://api.trello.com/1/members/me/boards?fields=name&filter=open&lists=open&key=e8b6ba838382302e68e9ad90a139bc7a&token=sometoken and gets 401. Maybe the key is disabled/broken/expired/etc? https://github.com/oskarjakiela/trello-web-clipper-firefox/blob/master/package.json#L26
